

service: functions

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource: "arn:aws:dynamodb:*:*:*"



package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  world:
    handler: bin/world
    events:
      - http:
          path: /world
          method: get
  addAuthor:
    handler: bin/addAuthor
    events:
      - http:
          path: /author
          method: post
  deleteAuthor:
    handler: bin/deleteAuthor
    events:
      - http:
          path: /author/{author_id}
          method: delete

  updateAuthor:
    handler: bin/updateAuthor
    events:
      - http:
          path: /author/{author_id}
          method: put

  getAuthor:
    handler: bin/getAuthor
    events:
      - http:
          path: /author/{author_id}
          method: get 
          cors: true

  getAuthorName:
    handler: bin/getAuthorName
    events:
      - http:
          path: /authorName/{author_id}
          method: get 

  addArticle:
    handler: bin/addArticle
    events:
      - http:
          path: /article
          method: post



resources:
  Resources:
    AuthorsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authors-table
        AttributeDefinitions:
          - AttributeName: author_id
            AttributeType: S
        KeySchema:
          - AttributeName: author_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ArticlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: articles-table
        AttributeDefinitions:
          - AttributeName: article_id
            AttributeType: S
        KeySchema:
          - AttributeName: article_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
