

service: functions

frameworkVersion: '2'

provider:
  name: aws
  runtime: go1.x
  lambdaHashingVersion: 20201221
  region: us-east-1

  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:*
      Resource:
        - arn:aws:dynamodb:us-east-1:601895526431:table/authors-table


package:
  patterns:
    - '!./**'
    - ./bin/**

functions:
  world:
    handler: bin/world
    events:
      - httpApi:
          path: /world
          method: get
  addAuthor:
    handler: bin/addAuthor
    events:
      - httpApi:
          path: /addAuthor
          method: post
  deleteAuthor:
    handler: bin/deleteAuthor
    events:
      - httpApi:
          path: /deleteAuthor/{author_id}
          method: delete

  updateAuthor:
    handler: bin/updateAuthor
    events:
      - httpApi:
          path: /updateAuthor/{author_id}
          method: put

  getAuthor:
    handler: bin/getAuthor
    events:
      - httpApi:
          path: /getAuthor/{author_id}
          method: get 



  getAuthorName:
    handler: bin/getAuthorName
    events:
      - httpApi:
          path: /getAuthorName/{author_id}
          method: get 

resources:
  Resources:
    AuthorsTable: 
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: authors-table
        AttributeDefinitions:
          - AttributeName: author_id
            AttributeType: S
        KeySchema:
          - AttributeName: author_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST

    ArticlesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: articles-table
        AttributeDefinitions:
          - AttributeName: article_id
            AttributeType: S
        KeySchema:
          - AttributeName: article_id
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
